### ISSUE TITLE
Start up crash on Galaxy Tab 3

### ISSUE THREAD

**Issue by D1ZY** [flyingdevelopmentstudio/infiniteflight-issues#1]
**Device**: Samsung Galaxy Tab 3 Lite
**Model**: SM1159
**OS Version**: Android 4.2.2

**Description**: Crash at launch of the app

**Comment by prollin** [comment]
Was able to reproduce this issue. A fix has been found and will be available in our next update.

**Comment by D1ZY** [comment]
Thank you.
