### ISSUE TITLE
Start Up crash Samsung Galaxy Tab 4- 7inch

### ISSUE THREAD

**Issue by D1ZY** [flyingdevelopmentstudio/infiniteflight-issues#6]
**Device** Samsung
**Model** Galaxy Tab 4 - 7inch SM- T230NU
**OS** Android 4.2.2
**Issue** App "crashes" every time launch is attempted. Similar to the Tab3Lite issue. 
**Troubleshooting** Tried restarting device power, attempted reinstallation multiple times. Still "crashes every time" it is tried to open.

**Comment by prollin** [comment]
This is most likely the same issue. It will be fixed in the upcoming release.

**Comment by D1ZY** [comment]
closing. :)
