### ISSUE TITLE
 Space Shuttle cannot be selected - multiple devices

### ISSUE THREAD

**Issue by D1ZY** [flyingdevelopmentstudio/infiniteflight-issues#7]
**Device** - Reported across all platforms, iPads, Samsung, LG etc.

**Model** - Affects at least all iOS devices, Several Android devices report same. Not model specific.

**OS** - iOS9.1, Android 4.2, 4.4, 5. 

**Issue** Upon selecting a mission for the Space Shuttle then "Fly" the app will close to device Home screens. 

**Troubleshooting** Device power restart, full app delete and re-installation have no impact and crash continues.

**Comment by prollin** [comment]
We have confirmed the issue and have a fix. It will be in the next update on Android, and the one after the upcoming one on iOS.
